/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    BetterAuthSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    Bucket: {
      name: string;
      type: "sst.aws.Bucket";
    };
    GithubClientId: {
      type: "sst.sst.Secret";
      value: string;
    };
    GithubClientSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleClientId: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleClientSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    Postgres: {
      database: string;
      host: string;
      password: string;
      port: number;
      type: "sst.aws.Postgres";
      username: string;
    };
    Vpc: {
      bastion: string;
      type: "sst.aws.Vpc";
    };
    Web: {
      type: "sst.aws.Nextjs";
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import "sst";
export {};
